repositories:
  - name: parity
    url: https://paritytech.github.io/helm-charts/

helmDefaults:
  createNamespace: false
  waitForJobs: true

releases:
  - name: validator-alice
    namespace: ziggy-pandora
    chart: parity/node
    version: 4.7.2
    values:
      - image:
          tag: v0.9.42
      - node:
          legacyRpcFlags: true
          replicas: 1
          customChainspecUrl: "https://purple-mathematical-cephalopod-484.mypinata.cloud/ipfs/QmRoeZNxMyZtaQQevpWPoWo6yRgpjnVtJTccxszaJ6M7Fj"
          forceDownloadChainspec: true
          role: authority
          flags:
            - "--alice"
          chainData:
            storageClass: do-block-storage
          perNodeServices:
            relayP2pService:
              enabled: true
              type: LoadBalancer
              ws:
                enabled: true
          allowUnsafeRpcMethods: true
  - name: validator-bob
    namespace: ziggy-pandora
    chart: parity/node
    version: 4.7.2
    values:
      - image:
          tag: v0.9.42
      - node:
          legacyRpcFlags: true
          replicas: 1
          flags:
            - "--bob"
            - --bootnodes "/ip4/178.128.139.214/tcp/30333/p2p/12D3KooWAqER4km9NPSeiSVRr2yKzq8VByLoFpwihny4C5dD2VZB"
          customChainspecUrl: "https://purple-mathematical-cephalopod-484.mypinata.cloud/ipfs/QmRoeZNxMyZtaQQevpWPoWo6yRgpjnVtJTccxszaJ6M7Fj"
          forceDownloadChainspec: true
          role: authority
          chainData:
            storageClass: do-block-storage
          perNodeServices:
            relayP2pService:
              enabled: true
              ws:
                enabled: true
          allowUnsafeRpcMethods: true
  - name: collator-car
    namespace: ziggy-pandora
    chart: parity/node
    version: 4.7.2
    values:
      - image:
          repository: freeverseio/laos-ownership-node
          tag: v0.0.3-dev
      - node:
          legacyRpcFlags: true
          command: "parachain-template-node"
          replicas: 1
          customChainspecUrl: "https://purple-mathematical-cephalopod-484.mypinata.cloud/ipfs/QmZbnMj6brwvTHTjYb5eDbaUZtiR7bZSVqoxLx2hmi1YBo"
          role: authority
          chainData:
            storageClass: do-block-storage
          perNodeServices:
            paraP2pService:
              enabled: true
              type: LoadBalancer
              ws:
                enabled: true
          allowUnsafeRpcMethods: true
          isParachain: true
          collatorRelayChain:
            customChainspecUrl: "https://purple-mathematical-cephalopod-484.mypinata.cloud/ipfs/QmRoeZNxMyZtaQQevpWPoWo6yRgpjnVtJTccxszaJ6M7Fj"
            chainData:
              storageClass: do-block-storage
            flags:
              - --bootnodes "/ip4/178.128.139.214/tcp/30333/p2p/12D3KooWAqER4km9NPSeiSVRr2yKzq8VByLoFpwihny4C5dD2VZB"
        
  # - name: public-node
  #   namespace: ziggy-pandora
  #   chart: parity/node
  #   version: 4.7.2
  #   values:
  #     - image:
  #         repository: freeverseio/laos-ownership-node
  #         tag: v0.0.3-dev
  #     - node:
  #         chain: arrakis
  #         legacyRpcFlags: true
  #         command: "parachain-template-node"
  #         replicas: 1
  #         chainData:
  #           storageClass: do-block-storage
  #         paraP2pService:
  #             enabled: true
  #             ws:
  #               enabled: true
  #         allowUnsafeRpcMethods: true
  #         isParachain: true
  #         collatorRelayChain:
  #           chainData:
  #             storageClass: do-block-storage
  #     - ingress:
  #         enabled: true
  #         annotations:
  #           kubernetes.io/ingress.class: "nginx"
  #           nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
  #           nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
  #           nginx.ingress.kubernetes.io/auth-tls-error-page: "http://www.mysite.com/error-cert.html"
  #           nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
  #           nginx.ingress.kubernetes.io/websocket-services: "public-node"
  #           cert-manager.io/cluster-issuer: letsencrypt-freeverse
  #         rules:
  #         - host: arrakis.gorengine.com
  #           http:
  #             paths:
  #             - path: /own
  #               pathType: Prefix
  #               backend:
  #                 service:
  #                   name: public-node
  #                   port:
  #                     name: websocket-rpc
  #         tls:
  #           - hosts:
  #             - arrakis.gorengine.com
  #             secretName: public-node-tls